-- 1. Create the 'licenses' table (or update it if exists - safer to recreate or alter)
-- For this script, we assume a fresh start or user manually handling table modifications.
-- Here is the complete modern schema.

create table if not exists public.licenses (
  id bigint generated by default as identity primary key,
  license_key text not null unique,
  is_active boolean default true,
  created_at timestamp with time zone default now(),
  hardware_id text,
  expiration_date timestamp with time zone
);

-- 1b. Ensure existing tables get required columns (idempotent)
alter table public.licenses add column if not exists is_active boolean default true;
alter table public.licenses add column if not exists created_at timestamp with time zone default now();
alter table public.licenses add column if not exists hardware_id text;
alter table public.licenses add column if not exists expiration_date timestamp with time zone;

-- 1c. Track license validation attempts for basic rate limiting
create table if not exists public.license_attempts (
  id bigint generated by default as identity primary key,
  license_key text not null unique,
  attempt_count integer not null default 0,
  first_attempt_at timestamp with time zone default now(),
  last_attempt_at timestamp with time zone default now(),
  last_hardware_id text
);

-- 2. Insert a test license key
insert into public.licenses (license_key, is_active)
values ('TEST-KEY-1234', true)
on conflict (license_key) do nothing;

-- 3. Create the 'accounts' table
create table if not exists public.accounts (
  id bigint generated by default as identity primary key,
  account_email text,
  cookie_data jsonb,
  account_status text default 'valid',
  platform text default 'netflix',
  last_used_at timestamp with time zone,
  created_at timestamp with time zone default now()
);

-- 4. Sample Account
insert into public.accounts (account_email, cookie_data, platform, account_status)
values (
  'test@example.com', 
  '[{"domain": ".netflix.com", "name": "test_cookie", "value": "test_value", "path": "/", "httpOnly": false, "secure": true}]'::jsonb, 
  'netflix', 
  'valid'
);

-- 5. Security hardening: lock down direct table access
alter table public.licenses enable row level security;
alter table public.accounts enable row level security;
alter table public.license_attempts enable row level security;

revoke all on table public.licenses from anon, authenticated;
revoke all on table public.accounts from anon, authenticated;
revoke all on table public.license_attempts from anon, authenticated;
